

const prompts = {
  start: [
    "Design a scene",
    "Create a setting",
    "Render a scene",
    "Craft an environment",
    "Build a space",
  ],
  source: [
    "from <i>Star Wars: The Mandalorian</i>",
    "from <i>Blade Runner 2049</i>",
    "from <i>The Matrix</i>",
    "from <i>Spirited Away</i>",
    "from <i>Half-Life 2</i>",
    "from <i>Jurassic Park</i>",
    "from <i>My Neighbor Totoro</i>",
    "from <i>The Shining</i>",
    "from <i>Bloodborne</i>",
    "from <i>Elden Ring</i>",
    "from <i>WandaVision</i>",
    "from <i>Arcane: League of Legends</i>",
    "from <i>Cyberpunk 2077</i>",
    "from <i>Stranger Things</i>",
    "from <i>Inside</i>",
    "from <i>Dark Souls</i>",
    "from <i>The Last of Us</i>",
    "from <i>The Legend of Zelda: Breath of the Wild</i>",
    "from <i>Disco Elysium</i>",
    "from <i>Mad Max: Fury Road</i>",
    "from <i>Nope</i>",
    "from <i>Everything Everywhere All at Once</i>",
    "from <i>Akira</i>",
    "from an <i>obscure 1970s sci-fi movie</i>",
    "from a <i>PS1-era horror game</i>",
    "from an <i>old black-and-white silent film</i>",
    "from a <i>found-footage horror movie</i>",
    "from a <i>dystopian 80s anime</i>",
    "from a <i>retro-futurist propaganda film</i>",
    "from a <i>liminal horror experience</i>"
],

  composition: [
      "framed as if viewed through a security camera",
      "from an extreme low angle",
      "from a top-down perspective like a strategy game",
      "as if filmed on a handheld camera",
      "as a single long take without cuts",
      "styled like a Renaissance painting",
      "composed entirely in silhouette",
      "seen as if through night vision goggles",
      "framed like a diorama",
      "seen from the perspective of a non-human observer",
      "as if seen through a keyhole",
      "with the camera locked in a fixed position",
      "styled like a motionless oil painting where the world moves around it",
      "as if the camera is floating slightly unsteadily, like a drone shot",
      "seen from an impossible Escher-like perspective",
      "with characters positioned symmetrically, like a <i>Wes Anderson</i> film",
      "as if viewed from behind glass, with reflections in the foreground",
      "with forced perspective that exaggerates depth"
  ],
  animation: [
      "where characters must loop seamlessly",
      "where background elements animate, but characters do not",
      "where reflections are a key animated element",
      "where the camera is the only animated element",
      "where characters move in exaggerated slow motion",
      "where physics simulations determine all motion",
      "where every animation follows a strict mechanical rhythm",
      "where lighting is the only animated element",
      "where objects animate in a staggered, stop-motion style",
      "where the world subtly distorts and breathes like a dream",
      "where time appears to stutter, like a corrupted video file",
      "where every motion has a slight delay, as if underwater",
      "where movement feels weightless, like zero gravity",
      "where gravity shifts unpredictably, objects floating at times",
      "where characters move like they are part of an old rotoscope animation",
      "where all motion accelerates and decelerates unnaturally",
      "where one element moves at a different frame rate than the rest",
      "where characters react to an unseen force"
  ],
  style: [
      "in a cel-shaded style reminiscent of <i>Studio Ghibli</i>",
      "in an early <i>PlayStation 1</i> aesthetic",
      "in a painterly, heavily textured style",
      "as if sculpted from clay",
      "using only black and white",
      "where every object is glowing",
      "as if underwater, with everything rippling",
      "where all textures are hand-drawn sketches",
      "in a retro <i>16-bit pixel-art</i> aesthetic",
      "in a style that feels like a <i>1930s Charlie Chaplin</i> film",
      "in a modeling and rendering style similar to <i>Disney's Beauty and the Beast</i>",
      "as if the entire scene is made of stained glass",
      "in a brutalist, dystopian style with stark concrete forms",
      "feeling big and cinematic like <i>The Godfather</i>",
      "as if painted in bold <i>Impressionist</i> brushstrokes",
      "as if everything is made of soft, plush fabric",
      "in the hyper-detailed style of a <i>Renaissance fresco</i>",
      "with an <i>80s neon grid</i> aesthetic",
      "as if built out of paper cutouts and stop-motion animated",
      "with every texture looking like rusted metal",
      "as if it was concept art that never became a real game",
      "in the washed-out, faded colors of an <i>old VHS tape</i>",
      "where every surface has the glossy perfection of a plastic toy",
      "as if sculpted from wax and half-melted",
      "like a <i>vaporwave album cover</i> brought to life",
      "in an old-school <i>pre-rendered CGI</i> style from the 90s",
      "in a gothic, over-embellished <i>Victorian</i> style",
      "where every material is made of glitching code"
  ],
  wildcard: [
    "And at least one material must be semi-transparent",
    "And all lighting must come from a single flickering source",
    "And the scene must include a hidden message",
    "And every object must have a face",
    "And nothing in the scene can have sharp edges",
    "And all materials must be reflective",
    "And the entire scene must be animated in reverse",
    "And every texture must be stretched to extreme proportions",
    "And the entire color palette must be shades of red",
    "And the environment must look abandoned and overgrown",
    "And everything must appear frozen in time",
    "And the scene must feel like it's deteriorating",
    "And one object must be impossibly large",
    "And at least one character or object must be floating",
    "And the sky must be an unnatural color",
    "And objects must duplicate and shift unpredictably",
    "And one object must be hyper-realistic while the rest are stylized",
    "And there must be a mysterious light source with no visible origin",
    "And something about the scene must subtly feel ‘off’",
    "And a small but constant movement should be present everywhere",
    "And part of the scene must seem to be looping like a broken record",
    "And one element must be untextured, standing out from the rest"
]
};

